from __future__ import annotations

from app.config import Settings


class CapabilityService:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    def capabilities(self) -> dict:
        return {
            "service": "go2-gateway",
            "version": self.settings.version,
            "robot_id": self.settings.robot_id,
            "mode": self.settings.mode,
            "gateway": {
                "methods": ["connect", "get_status", "stand", "sit", "stop", "move", "get_camera"],
                "sdk_wrapped": True,
            },
            "control": {
                "enabled": self.settings.control_enabled,
                "stand": True,
                "sit": True,
                "lie_down": True,
                "stop": True,
                "emergency_stop": True,
                "move": True,
                "max_vx": self.settings.max_vx,
                "max_vy": self.settings.max_vy,
                "max_wz": self.settings.max_wz,
                "min_move_duration": self.settings.min_move_duration,
                "max_move_duration": self.settings.max_move_duration,
            },
            "companion": {
                "implemented": True,
                "single_runtime": True,
                "start_url": "/api/v1/robot/companion/start",
                "stop_url": "/api/v1/robot/companion/stop",
                "resume_url": "/api/v1/robot/companion/resume",
                "status_url": "/api/v1/robot/companion/status",
                "manual_resume_after_preempt": True,
                "motion_path": "supervised_uwb_lidar_only",
            },
            "camera": {
                "snapshot": True,
                "stream": True,
                "snapshot_url": self.settings.camera_snapshot_url,
                "stream_url": self.settings.camera_stream_url,
                "stream_type": "mjpeg",
            },
            "voice": {
                "prompt": True,
                "mode": self.settings.voice_mode,
                "ready": self.settings.voice_mode.lower() == "mock" or bool(self.settings.voice_prompt_url),
                "status_url": "/api/voice/status",
                "fall_prompt": self.settings.fall_prompt,
                "prompt_url_configured": bool(self.settings.voice_prompt_url),
                "speech_recognition": False,
                "real_asr": False,
                "robot_speaker": self.settings.voice_mode != "mock" or bool(self.settings.voice_prompt_url),
                "elder_response": True,
                "elder_response_url": "/api/robot/tasks/{task_id}/elder-response",
                "elder_response_timeout_seconds": self.settings.elder_response_timeout_seconds,
            },
            "tasks": {
                "confirm_fall": "implemented",
                "confirm_fall_state_machine": {
                    "statuses": ["QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", "BLOCKED"],
                    "steps": [
                        "RECEIVED",
                        "PREFLIGHT",
                        "MOVING",
                        "ARRIVED",
                        "CAMERA_CHECK",
                        "VOICE_PROMPT",
                        "WAITING_RESPONSE",
                        "REPORTING",
                    ],
                    "outcomes": ["SAFE", "NEED_HELP", "NO_RESPONSE", "UNKNOWN"],
                },
                "move_to_target": "implemented",
                "follow": "reserved",
                "patrol": "reserved",
                "inspection": "reserved",
                "confirm_fall_statuses": ["waiting", "running", "moving", "arrived", "checking", "finished", "failed", "cancelled"],
                "terminal_statuses": ["finished", "failed", "cancelled"],
                "terminal_restore_from_audit": self.settings.task_audit_enabled,
                "queueing": "fifo_waiting_tasks",
                "queue_fields": ["queue_position", "queue_size", "queue_head", "blocked_by_task_id", "queue"],
                "locations_url": "/api/locations",
                "location_resolve_url": "/api/locations/resolve?location={location}",
                "urls": {
                    "list": "/api/tasks",
                    "summary": "/api/tasks/summary",
                    "latest": "/api/tasks/latest",
                    "active": "/api/tasks/active",
                    "queue": "/api/tasks/queue",
                    "external_lookup": "/api/tasks/external/{external_task_id}",
                    "external_status": "/api/tasks/external/{external_task_id}/status",
                    "external_result": "/api/tasks/external/{external_task_id}/result",
                    "external_timeline": "/api/tasks/external/{external_task_id}/timeline",
                    "external_audit_log": "/api/tasks/external/{external_task_id}/audit-log",
                    "external_feedback_replay": "/api/tasks/external/{external_task_id}/feedback/replay",
                    "external_voice_result": "/api/tasks/external/{external_task_id}/voice-result",
                    "external_cancel": "/api/tasks/external/{external_task_id}/cancel",
                    "confirm_fall": "/api/tasks/confirm-fall",
                    "target_move": "/api/tasks/target-move",
                    "status": "/api/tasks/{task_id}/status",
                    "result": "/api/tasks/{task_id}/result",
                    "timeline": "/api/tasks/{task_id}/timeline",
                    "task_audit_log": "/api/tasks/{task_id}/audit-log",
                    "feedback_replay": "/api/tasks/{task_id}/feedback/replay",
                    "callbacks_replay": "/api/robot/tasks/{task_id}/callbacks/replay",
                    "callback_deliveries": "/api/robot/tasks/{task_id}/callback-deliveries",
                    "elder_response": "/api/robot/tasks/{task_id}/elder-response",
                    "arrival_evidence": "/api/robot/tasks/{task_id}/evidence/arrival.jpg",
                    "cancel": "/api/tasks/{task_id}/cancel",
                    "voice_result": "/api/tasks/{task_id}/voice-result",
                    "audit_log": "/api/tasks/audit-log",
                },
                "source_fields": self._source_fields(),
            },
            "events": {
                "fall": {
                    "implemented": True,
                    "submit_url": "/api/events/fall",
                    "lookup_url": "/api/events/fall/{source_event_id}",
                    "idempotency_key": "source_event_id",
                    "idempotency_aliases": ["source_event_id", "sourceEventId", "event_id", "eventId", "camera_event_id", "cameraEventId"],
                    "callback_url_replay_attach": True,
                    "external_task_id_idempotency": True,
                }
            },
            "status": {
                "health_url": "/health",
                "preflight_url": "/api/preflight",
                "preflight_compat_url": "/api/robot/preflight",
                "compact_url": "/api/status",
                "detail_url": "/api/robot/status",
                "lidar_url": "/api/lidar/status",
                "robot_lidar_url": "/api/robot/lidar/status",
                "readiness_url": "/api/readiness",
                "readiness_compat_url": "/api/robot/readiness",
                "connection_url": "/api/connection",
                "task_context_fields": self._source_fields(),
            },
            "feedback": {
                "query": True,
                "callback": bool(self.settings.health_new_callback_url),
                "callback_delivery_tracking": True,
                "event_callback_url": True,
                "status_url": "/api/feedback/status",
                "replay_url": "/api/tasks/{task_id}/feedback/replay",
                "callbacks_replay_url": "/api/robot/tasks/{task_id}/callbacks/replay",
                "callback_deliveries_url": "/api/robot/tasks/{task_id}/callback-deliveries",
                "callback_source_fields": self._source_fields(),
                "audit_log": self.settings.task_audit_enabled,
            },
            "task_evidence": {
                "arrival_snapshot": True,
                "arrival_snapshot_url": "/api/robot/tasks/{task_id}/evidence/arrival.jpg",
                "returns_local_absolute_path": False,
            },
            "navigation": {
                "slam": False,
                "slam_navigation": False,
                "path_planning": False,
                "fixed_motion_plan": True,
                "scripted_motion": True,
                "configurable_motion_plan": bool(self.settings.location_motion_plans_json),
            },
            "lidar": {
                "status": "implemented",
                "status_url": "/api/lidar/status",
                "robot_status_url": "/api/robot/lidar/status",
                "read_only": True,
                "mapping_prerequisites_probe": True,
                "mapping_start": False,
                "mapping_stop": False,
                "localization_start": False,
                "goal_dispatch": False,
                "cruise": False,
            },
            "real_asr": False,
        }

    def _source_fields(self) -> list[str]:
        return [
            "elder_id",
            "location",
            "location_resolution",
            "confidence",
            "source_event_id",
            "camera_id",
            "external_task_id",
        ]
