from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    ROBOT_OFFLINE = "ROBOT_OFFLINE"
    ROBOT_STATE_STALE = "ROBOT_STATE_STALE"
    DDS_NOT_READY = "DDS_NOT_READY"
    SDK_NOT_INITIALIZED = "SDK_NOT_INITIALIZED"
    SDK_TIMEOUT = "SDK_TIMEOUT"
    SDK_COMMAND_FAILED = "SDK_COMMAND_FAILED"
    CONTROL_BUSY = "CONTROL_BUSY"
    CONTROL_DISABLED = "CONTROL_DISABLED"
    READ_ONLY_MODE = "READ_ONLY_MODE"
    PREFLIGHT_FAILED = "PREFLIGHT_FAILED"
    LOCATION_PLAN_NOT_VALIDATED = "LOCATION_PLAN_NOT_VALIDATED"
    INVALID_MOTION_PARAMETER = "INVALID_MOTION_PARAMETER"
    CAMERA_UNAVAILABLE = "CAMERA_UNAVAILABLE"
    CAMERA_DECODE_FAILED = "CAMERA_DECODE_FAILED"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_NOT_SUPPORTED = "TASK_NOT_SUPPORTED"
    TASK_STATE_CONFLICT = "TASK_STATE_CONFLICT"
    EMERGENCY_STOPPED = "EMERGENCY_STOPPED"
    INVALID_REQUEST = "INVALID_REQUEST"
    SERVICE_RESTART_INTERRUPTED = "SERVICE_RESTART_INTERRUPTED"
    UWB_NOT_READY = "UWB_NOT_READY"
    LIDAR_NOT_READY = "LIDAR_NOT_READY"
    LIDAR_STOP_ACTIVE = "LIDAR_STOP_ACTIVE"
    RISK_NOT_READY = "RISK_NOT_READY"
    FALL_LOCK_ACTIVE = "FALL_LOCK_ACTIVE"
    MANUAL_TAKEOVER_ACTIVE = "MANUAL_TAKEOVER_ACTIVE"
    COMPANION_STATE_CONFLICT = "COMPANION_STATE_CONFLICT"
    COMPANION_RUNTIME_FAILED = "COMPANION_RUNTIME_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class GatewayError(RuntimeError):
    def __init__(self, code: ErrorCode, message: str, http_status: int = 400) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.http_status = http_status
